
ENGINE:
 - MASSCAN_BIN_PATH: /usr/bin/masscan
 - NMAP_BIN_PATH: /usr/bin/nmap

SECRET_KEY: F5XazmTEJKAugRJ0MHkLMlyfqMT3ts6SNXrbGnNTY1nzoW8uQ
LOG_LEVEL: DEBUG
DEBUG: true
DB_ENGINE: mysql
DB_HOST: 10.27.106.248
DB_PORT: 3306
DB_USER: root
DB_PASSWORD: test@1q2w2e4R
DB_NAME: xscan
DB_CHARSET: utf8
REDIS_HOST: 10.27.106.248
REDIS_PORT: 6379
REDIS_PASSWORD: sqsjywl123
REDIS_DB_CACHE: 8
REDIS_DB_CELERY: 5
DISPLAY_PER_PAGE: 25
DEFAULT_EXPIRED_YEARS: 70

SITE_NAME: 资产探测API管理系统


